# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [212]:
# import numpy and pandas
import pandas as pd
import numpy as np

# Challenge 1 - Index Functions

In this challenge, we will practice the advanced functions introduced in the lesson. However, before we start, we will load and evaluate our dataset.

In [213]:
# Run this code:

admissions = pd.read_csv('../Admission_Predict.csv')
#to remove trailing spaces at the end of the column names
admissions.columns = admissions.columns.str.rstrip()

Let's evaluate the dataset by looking at the `head` function.

In [214]:
# Your code here:
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90

Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [215]:
# Your code here:
admissions.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [216]:
# Your code here:
admissions.index = admissions['Serial No.']
#other option:
#admissions.set_index('Serial No.',inplace=True)

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

In [217]:
# Your code here:
ad = list(zip(admissions['GRE Score'],admissions['CGPA']))
len(ad) == len(admissions['Serial No.'])

True

In [218]:
'''
len(admissions['GRE Score']) == len(admissions['GRE Score'].unique())
len(admissions['CGPA']) == len(admissions['CGPA'].unique())
'''

"\nlen(admissions['GRE Score']) == len(admissions['GRE Score'].unique())\nlen(admissions['CGPA']) == len(admissions['CGPA'].unique())\n"

Replace the index with an index comprised of two columns - `GRE Score` and `CGPA`. Remove the columns from the dataset as well. Make sure to use `inplace=True`.

In [219]:
#admissions['ScoreCGPA'] = admissions['GRE Score']+'-'+admissions['CGPA']

In [220]:
admissions.set_index(['CGPA','GRE Score'],inplace=True)

In [221]:
admissions

,,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
CGPA,GRE Score,,,,,,,
9.65,337,1,118,4,4.5,4.5,1,0.92
8.00,316,2,104,3,3.0,3.5,1,0.72
8.67,322,3,110,3,3.5,2.5,1,0.80
8.21,314,4,103,2,2.0,3.0,0,0.65
9.34,330,5,115,5,4.5,3.0,1,0.90
8.20,321,6,109,3,3.0,4.0,1,0.75
7.90,308,7,101,2,3.0,4.0,0,0.68
8.00,302,8,102,1,2.0,1.5,0,0.50
8.60,323,9,108,3,3.5,3.0,0,0.45
9.00,327,10,111,4,4.0,4.5,1,0.84
9.10,328,11,112,4,4.0,4.5,1,0.78
8.00,307,12,109,3,4.0,3.0,1,0.62
8.20,311,13,104,3,3.5,2.0,1,0.61
8.30,314,14,105,3,3.5,2.5,0,0.54
8.70,317,15,107,3,4.0,3.0,0,0.66
8.00,319,16,106,3,4.0,3.0,1,0.65
8.80,318,17,110,3,4.0,3.0,0,0.63
8.50,303,18,102,3,3.5,3.0,0,0.62
8.40,325,19,114,4,3.0,2.0,0,0.70
9.50,328,20,116,5,5.0,5.0,1,0.94
9.70,334,21,119,5,5.0,4.5,1,0.95
9.80,336,22,119,5,4.0,3.5,1,0.97
8.80,322,23,109,5,4.5,3.5,0,0.76
7.50,298,24,98,2,1.5,2.5,1,0.44
7.20,295,25,93,1,2.0,2.0,0,0.46
7.30,310,26,99,2,1.5,2.0,0,0.54
8.10,300,27,97,2,3.0,3.0,1,0.65
8.30,327,28,103,3,4.0,4.0,1,0.74
9.40,338,29,118,4,3.0,4.5,1,0.91
9.60,340,30,114,5,4.0,4.0,1,0.90
...,...,...,...,...,...,...,...,...
8.24,310,356,103,2,2.5,2.5,0,0.72
9.22,324,357,110,3,3.5,3.0,1,0.89
9.62,336,358,119,4,4.5,4.0,1,0.95
8.54,321,359,109,3,3.0,3.0,1,0.79
7.65,315,360,105,2,2.0,2.5,0,0.39
7.66,304,361,101,2,2.0,2.5,0,0.38
7.43,297,362,96,2,2.5,2.0,0,0.34
7.56,290,363,100,1,1.5,2.0,0,0.47
7.65,303,364,98,1,2.0,2.5,0,0.56
8.43,311,365,99,1,2.5,3.0,1,0.71
8.84,322,366,104,3,3.5,4.0,1,0.78
8.67,319,367,105,3,3.0,3.5,1,0.73
9.15,324,368,110,4,4.5,4.0,1,0.82
8.26,300,369,100,3,3.0,3.5,0,0.62
9.74,340,370,113,4,5.0,5.0,1,0.96
9.82,335,371,117,5,5.0,5.0,1,0.96
7.96,302,372,101,2,2.5,3.5,0,0.46
8.10,307,373,105,2,2.0,3.5,0,0.53
7.80,296,374,97,2,1.5,2.0,0,0.49
8.44,320,375,108,3,3.5,4.0,1,0.76
8.24,314,376,102,2,2.0,2.5,0,0.64
8.65,318,377,106,3,2.0,3.0,0,0.71
9.12,326,378,112,4,4.0,3.5,1,0.84
8.76,317,379,104,2,3.0,3.0,0,0.77
9.23,329,380,111,4,4.5,4.0,1,0.89
9.04,324,381,110,3,3.5,3.5,1,0.82
9.11,325,382,107,3,3.0,3.5,1,0.84
9.45,330,383,116,4,5.0,4.5,1,0.91
8.78,312,384,103,3,3.5,4.0,0,0.67
9.66,333,385,117,4,5.0,4.0,1,0.95

In [222]:
#admissions['ScoreCGPA'] = ad
#admissions.set_index('ScoreCGPA',inplace=True)
#admissions

In [223]:
#admissions = admissions.drop('GRE Score',1)
#admissions = admissions.drop('CGPA',1)
#admissions = admissions.drop('Serial No.',1)?

Now change the index back to a sequence starting at zero using the `reset_index` function. Make sure to use `inplace=True`.

In [224]:
# Your code here:
admissions.reset_index(inplace=True)
admissions.head()

,CGPA,GRE Score,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
0,9.65,337,1,118,4,4.5,4.5,1,0.92
1,8.00,316,2,104,3,3.0,3.5,1,0.72
2,8.67,322,3,110,3,3.5,2.5,1,0.80
3,8.21,314,4,103,2,2.0,3.0,0,0.65
4,9.34,330,5,115,5,4.5,3.0,1,0.90

# Challenge 2 - Advanced Functions

In this part of the lab, we would like to test complex conditions on the entire dataset at once. Let's start by finding the number of rows where the CGPA is higher than 9 and the student has conducted research.

In [225]:
# Your code here:
admissions[(admissions.CGPA >9)&(admissions.Research!=0)].shape

(101, 9)

Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [226]:
# Your code here:
#admissions[(admissions.CGPA >9)&(admissions.SOP>3.5)]
admissions[(admissions.CGPA >9)&(admissions.SOP>3.5)] #['Chance of Admit'].mean()

,CGPA,GRE Score,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
0,9.65,337,1,118,4,4.5,4.5,1,0.92
4,9.34,330,5,115,5,4.5,3.0,1,0.90
10,9.10,328,11,112,4,4.0,4.5,1,0.78
19,9.50,328,20,116,5,5.0,5.0,1,0.94
20,9.70,334,21,119,5,5.0,4.5,1,0.95
21,9.80,336,22,119,5,4.0,3.5,1,0.97
29,9.60,340,30,114,5,4.0,4.0,1,0.90
30,9.80,331,31,112,5,4.0,5.0,1,0.94
31,9.20,320,32,110,5,5.0,5.0,1,0.88
39,9.10,332,40,117,4,4.5,4.0,0,0.87
40,9.40,326,41,113,5,4.5,4.0,1,0.91
41,9.10,322,42,110,5,5.0,4.0,1,0.88
42,9.30,329,43,114,5,4.0,5.0,1,0.86
43,9.70,339,44,119,5,4.5,4.0,0,0.89
65,9.16,328,66,115,4,4.5,4.0,1,0.78
66,9.64,332,67,118,5,5.0,5.0,1,0.94
67,9.76,336,68,112,5,5.0,5.0,1,0.96
68,9.45,321,69,111,5,5.0,5.0,1,0.93
69,9.04,314,70,108,4,4.5,4.0,1,0.84
77,9.50,340,78,120,4,5.0,5.0,1,0.96
78,9.22,320,79,110,5,5.0,4.5,1,0.92
79,9.36,322,80,115,5,4.0,4.5,1,0.92
80,9.45,340,81,115,5,4.5,4.5,1,0.94
93,9.24,332,94,119,4,5.0,4.5,1,0.90
101,9.18,329,102,111,4,4.5,4.5,1,0.87
103,9.38,331,104,116,5,5.0,5.0,1,0.93
110,9.04,310,111,106,4,4.5,4.5,1,0.66
115,9.56,335,116,117,5,5.0,5.0,1,0.94
116,9.48,334,117,119,5,4.5,4.5,1,0.94
121,9.32,323,122,113,3,4.0,3.0,1,0.85
...,...,...,...,...,...,...,...,...,...
225,9.19,329,226,114,5,4.5,5.0,1,0.86
233,9.02,328,234,110,4,4.0,2.5,1,0.81
241,9.68,335,242,115,4,4.5,4.5,1,0.93
242,9.12,321,243,114,4,4.0,5.0,0,0.85
246,9.34,331,247,119,4,5.0,4.5,1,0.90
247,9.13,327,248,108,5,5.0,3.5,1,0.87
255,9.14,327,256,113,4,4.5,5.0,0,0.83
263,9.45,329,264,113,5,5.0,4.5,1,0.89
268,9.11,317,269,110,3,4.0,4.5,1,0.80
271,9.66,340,272,112,4,5.0,4.5,1,0.94
272,9.26,331,273,116,5,4.0,4.0,1,0.93
273,9.19,336,274,118,5,4.5,4.0,1,0.92
274,9.08,324,275,114,5,5.0,4.5,1,0.89
275,9.02,314,276,104,4,5.0,5.0,0,0.82
284,9.11,320,285,120,3,4.0,4.5,0,0.86
285,9.24,330,286,114,3,4.5,4.5,1,0.90
293,9.10,323,294,110,3,4.0,3.5,1,0.79
298,9.18,328,299,108,4,4.5,4.0,1,0.84
322,9.47,332,323,118,5,5.0,5.0,1,0.94
346,9.54,334,347,116,4,4.0,3.5,1,0.93
347,9.23,338,348,115,5,4.5,5.0,1,0.91
350,9.17,330,351,114,4,4.5,3.0,1,0.86
357,9.62,336,358,119,4,4.5,4.0,1,0.95
367,9.15,324,368,110,4,4.5,4.0,1,0.82
369,9.74,340,370,113,4,5.0,5.0,1,0.96
370,9.82,335,371,117,5,5.0,5.0,1,0.96
377,9.12,326,378,112,4,4.0,3.5,1,0.84
379,9.23,329,380,111,4,4.5,4.0,1,0.89
382,9.45,330,383,116,4,5.0,4.5,1,0.91
384,9.66,333,385,117,4,5.0,4.0,1,0.95

We would like to create a deciding factor column for each student. We standardize several columns and then pick the most important factor from a lookup table. If the standardized value is above 0.8, the student will be accepted.

We will start by creating a standardized column for `CGPA`, `GRE Score` and `LOR`. We will name these columns `CGPA_std`, `GRE_std`, and `LOR_std` respecively.

Recall that standardizing a column is done by subtracting the mean of the column from all observations in the column and then dividing each observation in the column by the column's standard deviation.

In the cell below, write a standardization function (a function that takes a column as input and returns a standardized column as output). Make sure to use the `numpy` versions of mean and standard deviation.

In [227]:
def standardize(column):
    # This function takes a column from a dataframe and returns a 
    # standardized column by subtracting the column's mean
    # and dividing by the column's standard deviation.
    
    # Your code here:
    return column - column.mean()/column.std()

Now create the standardized columns `CGPA_std`, `GRE_std`, and `LOR_std` and add them to the `admissions` dataframe.

In [194]:
# Your code here:
"""
CGPA_std = standardize(admissions['CGPA'])
GRE_std = standardize(admissions['GRE Score'])
LOR_std = standardize(admissions['LOR'])
"""

"\nCGPA_std = standardize(admissions['CGPA'])\nGRE_std = standardize(admissions['GRE Score'])\nLOR_std = standardize(admissions['LOR'])\n"

In [228]:
admissions = admissions.assign(CGPA_std=standardize(admissions['CGPA']),
                  GRE_std=standardize(admissions['GRE Score']),
                  LOR_std=standardize(admissions['LOR']))

We will generate the decision choice at random using the code below. Please run the cell.

In [229]:
# Run this code:

from random import choices
std_columns = ['CGPA_std', 'GRE_std', 'LOR_std']

decision_choice = choices(std_columns, k=admissions.shape[0])

Now create the deciding column using the `lookup` function. The lookup column is `decision_choice` found above. Call the column resulting from the lookup function `deciding_column` and add it to the `admissions` dataframe.

In [230]:
admissions.head()

,CGPA,GRE Score,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit,CGPA_std,GRE_std,LOR_std
0,9.65,337,1,118,4,4.5,4.5,1,0.92,-4.621747,309.598899,0.674568
1,8.00,316,2,104,3,3.0,3.5,1,0.72,-6.271747,288.598899,-0.325432
2,8.67,322,3,110,3,3.5,2.5,1,0.80,-5.601747,294.598899,-1.325432
3,8.21,314,4,103,2,2.0,3.0,0,0.65,-6.061747,286.598899,-0.825432
4,9.34,330,5,115,5,4.5,3.0,1,0.90,-4.931747,302.598899,-0.825432

In [231]:
# Your code here:
#deciding_column = admissions.lookup(admissions.index,decision_choice) 
deciding_column = admissions.lookup(admissions.index,decision_choice)

In [234]:
admissions['deciding_column'] = deciding_column
admissions

,CGPA,GRE Score,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit,CGPA_std,GRE_std,LOR_std,deciding_column
0,9.65,337,1,118,4,4.5,4.5,1,0.92,-4.621747,309.598899,0.674568,309.598899
1,8.00,316,2,104,3,3.0,3.5,1,0.72,-6.271747,288.598899,-0.325432,-6.271747
2,8.67,322,3,110,3,3.5,2.5,1,0.80,-5.601747,294.598899,-1.325432,294.598899
3,8.21,314,4,103,2,2.0,3.0,0,0.65,-6.061747,286.598899,-0.825432,286.598899
4,9.34,330,5,115,5,4.5,3.0,1,0.90,-4.931747,302.598899,-0.825432,302.598899
5,8.20,321,6,109,3,3.0,4.0,1,0.75,-6.071747,293.598899,0.174568,293.598899
6,7.90,308,7,101,2,3.0,4.0,0,0.68,-6.371747,280.598899,0.174568,280.598899
7,8.00,302,8,102,1,2.0,1.5,0,0.50,-6.271747,274.598899,-2.325432,274.598899
8,8.60,323,9,108,3,3.5,3.0,0,0.45,-5.671747,295.598899,-0.825432,-5.671747
9,9.00,327,10,111,4,4.0,4.5,1,0.84,-5.271747,299.598899,0.674568,299.598899
10,9.10,328,11,112,4,4.0,4.5,1,0.78,-5.171747,300.598899,0.674568,0.674568
11,8.00,307,12,109,3,4.0,3.0,1,0.62,-6.271747,279.598899,-0.825432,-0.825432
12,8.20,311,13,104,3,3.5,2.0,1,0.61,-6.071747,283.598899,-1.825432,283.598899
13,8.30,314,14,105,3,3.5,2.5,0,0.54,-5.971747,286.598899,-1.325432,-1.325432
14,8.70,317,15,107,3,4.0,3.0,0,0.66,-5.571747,289.598899,-0.825432,-5.571747
15,8.00,319,16,106,3,4.0,3.0,1,0.65,-6.271747,291.598899,-0.825432,-0.825432
16,8.80,318,17,110,3,4.0,3.0,0,0.63,-5.471747,290.598899,-0.825432,-5.471747
17,8.50,303,18,102,3,3.5,3.0,0,0.62,-5.771747,275.598899,-0.825432,275.598899
18,8.40,325,19,114,4,3.0,2.0,0,0.70,-5.871747,297.598899,-1.825432,297.598899
19,9.50,328,20,116,5,5.0,5.0,1,0.94,-4.771747,300.598899,1.174568,-4.771747
20,9.70,334,21,119,5,5.0,4.5,1,0.95,-4.571747,306.598899,0.674568,0.674568
21,9.80,336,22,119,5,4.0,3.5,1,0.97,-4.471747,308.598899,-0.325432,-0.325432
22,8.80,322,23,109,5,4.5,3.5,0,0.76,-5.471747,294.598899,-0.325432,294.598899
23,7.50,298,24,98,2,1.5,2.5,1,0.44,-6.771747,270.598899,-1.325432,-6.771747
24,7.20,295,25,93,1,2.0,2.0,0,0.46,-7.071747,267.598899,-1.825432,-7.071747
25,7.30,310,26,99,2,1.5,2.0,0,0.54,-6.971747,282.598899,-1.825432,-1.825432
26,8.10,300,27,97,2,3.0,3.0,1,0.65,-6.171747,272.598899,-0.825432,-0.825432
27,8.30,327,28,103,3,4.0,4.0,1,0.74,-5.971747,299.598899,0.174568,299.598899
28,9.40,338,29,118,4,3.0,4.5,1,0.91,-4.871747,310.598899,0.674568,0.674568
29,9.60,340,30,114,5,4.0,4.0,1,0.90,-4.671747,312.598899,0.174568,0.174568
...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,8.24,310,356,103,2,2.5,2.5,0,0.72,-6.031747,282.598899,-1.325432,-6.031747
356,9.22,324,357,110,3,3.5,3.0,1,0.89,-5.051747,296.598899,-0.825432,296.598899
357,9.62,336,358,119,4,4.5,4.0,1,0.95,-4.651747,308.598899,0.174568,0.174568
358,8.54,321,359,109,3,3.0,3.0,1,0.79,-5.731747,293.598899,-0.825432,-0.825432
359,7.65,315,360,105,2,2.0,2.5,0,0.39,-6.621747,287.598899,-1.325432,-1.325432
360,7.66,304,361,101,2,2.0,2.5,0,0.38,-6.611747,276.598899,-1.325432,276.598899
361,7.43,297,362,96,2,2.5,2.0,0,0.34,-6.841747,269.598899,-1.825432,-1.825432
362,7.56,290,363,100,1,1.5,2.0,0,0.47,-6.711747,262.598899,-1.825432,262.598899
363,7.65,303,364,98,1,2.0,2.5,0,0.56,-6.621747,275.598899,-1.325432,275.598899
364,8.43,311,365,99,1,2.5,3.0,1,0.71,-5.841747,283.598899,-0.825432,283.598899
365,8.84,322,366,104,3,3.5,4.0,1,0.78,-5.431747,294.598899,0.174568,294.598899
366,8.67,319,367,105,3,3.0,3.5,1,0.73,-5.601747,291.598899,-0.325432,291.598899
367,9.15,324,368,110,4,4.5,4.0,1,0.82,-5.121747,296.598899,0.174568,0.174568
368,8.26,300,369,100,3,3.0,3.5,0,0.62,-6.011747,272.598899,-0.325432,-0.325432
369,9.74,340,370,113,4,5.0,5.0,1,0.96,-4.531747,312.598899,1.174568,312.598899
370,9.82,335,371,117,5,5.0,5.0,1,0.96,-4.451747,307.598899,1.174568,307.598899
371,7.96,302,372,101,2,2.5,3.5,0,0.46,-6.311747,274.598899,-0.325432,274.598899
372,8.10,307,373,105,2,2.0,3.5,0,0.53,-6.171747,279.598899,-0.325432,-6.171747
373,7.80,296,374,97,2,1.5,2.0,0,0.49,-6.471747,268.598899,-1.825432,-1.825432
374,8.44,320,375,108,3,3.5,4.0,1,0.76,-5.831747,292.598899,0.174568,292.598899
375,8.24,314,376,102,2,2.0,2.5,0,0.64,-6.031747,286.598899,-1.325432,286.598899
376,8.65,318,377,106,3,2.0,3.0,0,0.71,-5.621747,290.598899,-0.825432,-5.621747
377,9.12,326,378,112,4,4.0,3.5,1,0.84,-5.151747,298.598899,-0.325432,-5.151747
378,8.76,317,379,104,2,3.0,3.0,0,0.77,-5.511747,289.598899,-0.825432,-0.825432
379,9.23,329,380,111,4,4.5,4.0,1,0.89,-5.041747,301.598899,0.174568,301.598899
380,9.04,324,381,110,3,3.5,3.5,1,0.82,-5.231747,296.598899,-0.325432,296.598899
381,9.11,325,382,107,3,3.0,3.5,1,0.84,-5.161747,297.598899,-0.325432,297.598899
382,9.45,330,383,116,4,5.0,4.5,1,0.91,-4.821747,302.598899,0.674568,0.674568
383,8.78,312,384,103,3,3.5,4.0,0,0.67,-5.491747,284.598899,0.174568,-5.491747
384,9.66,333,385,117,4,5.0,4.0,1,0.95,-4.611747,305.598899,0.174568,305.598899

Create a column called `decision` in the `admissions` dataframe. Assign 1 to this column if the value of `deciding_column` is greater than 0.8 and 0 otherwise.

In [245]:
# Your code here:
#np version
admissions['decision'] = np.where(admissions.deciding_column>0.8,1,0)
admissions.head()
#pd version
#admissions['deciding_column']/admissions['deciding_column'].where(admissions['deciding_column']>0.8,a-1)

,CGPA,GRE Score,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit,CGPA_std,GRE_std,LOR_std,deciding_column,decision
0,9.65,337,1,118,4,4.5,4.5,1,0.92,-4.621747,309.598899,0.674568,309.598899,1
1,8.00,316,2,104,3,3.0,3.5,1,0.72,-6.271747,288.598899,-0.325432,-6.271747,0
2,8.67,322,3,110,3,3.5,2.5,1,0.80,-5.601747,294.598899,-1.325432,294.598899,1
3,8.21,314,4,103,2,2.0,3.0,0,0.65,-6.061747,286.598899,-0.825432,286.598899,1
4,9.34,330,5,115,5,4.5,3.0,1,0.90,-4.931747,302.598899,-0.825432,302.598899,1

How many applicants will be accepted to the program using the decision column? Compute the result below.

In [259]:
# Your code here:
admissions[(admissions.decision == 1)].shape

(148, 14)

In [260]:
#ou plus simple :
admissions.decision.sum()

148

# Challenge 3 - Method Chaining

To increase our coding efficiency, let's make a number of changes to our dataframe in one line of code.

In the cell below, remove all non character symbols from the column names, replace all spaces in column names to underscores, and change all upper case characters to lower case. Assign these new column values to `admissions.columns`.

In [258]:
# Your code here:
admissions.columns = admissions.columns.str.replace(' ','_').str.replace('.','').str.lower()
admissions.columns

Index(['cgpa', 'gre_score', 'serial_no', 'toefl_score', 'university_rating',
       'sop', 'lor', 'research', 'chance_of_admit', 'cgpa_std', 'gre_std',
       'lor_std', 'deciding_column', 'decision'],
      dtype='object')

In the cell below, give all student with a university rating of 4 or higher a 10 point boost on their GRE score and split the column into 4 bins using the `cut` function. Assign this new score to the variable `adjusted_gre`.

In [293]:
# Your code here:
mpg_labels = ['Very Low', 'Low', 'High', 'Very High']
admissions['adjusted_gre'] = pd.cut(admissions.assign(gre_score=admissions.gre_score.where(
    admissions.university_rating<4, admissions.gre_score+10, axis=0))
                                    .gre_score, 4, labels=mpg_labels)

In [295]:
admissions.head()

,cgpa,gre_score,serial_no,toefl_score,university_rating,sop,lor,research,chance_of_admit,cgpa_std,gre_std,lor_std,deciding_column,decision,adjusted_gre
0,9.65,337,1,118,4,4.5,4.5,1,0.92,-4.621747,309.598899,0.674568,309.598899,1,Very High
1,8.00,316,2,104,3,3.0,3.5,1,0.72,-6.271747,288.598899,-0.325432,-6.271747,0,Low
2,8.67,322,3,110,3,3.5,2.5,1,0.80,-5.601747,294.598899,-1.325432,294.598899,1,High
3,8.21,314,4,103,2,2.0,3.0,0,0.65,-6.061747,286.598899,-0.825432,286.598899,1,Low
4,9.34,330,5,115,5,4.5,3.0,1,0.90,-4.931747,302.598899,-0.825432,302.598899,1,Very High